-- Core
require("core.options")
require("core.keymaps")
require("core.colorscheme")

-- PLugins
require("plugins_setup")
require("plugins.nvim_cmp")
require("plugins.lsp.mason")
require("plugins.lsp.lspconfig")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.autopairs")
require("plugins.surround")
require("plugins.comment")
require("plugins.gitsigns")
require("plugins.nvim_tree")
require("plugins.lualine")
require("plugins.bufferline")
require("plugins.indent_blankline")
require("plugins.todo_comments")
require("plugins.toggleterm")
require("plugins.which_key")
